"""Add allowed endpoints

Revision ID: 21a5a21efc5a
Revises: a484e56750ab
Create Date: 2026-05-15 13:26:35.568388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a5a21efc5a'
down_revision: Union[str, None] = 'a484e56750ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allowed_endpoints', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allowed_endpoints')
    # ### end Alembic commands ###