"""Added hardware linking and physical pins to relays

Revision ID: 21f4a9cd923b
Revises: 265c50853d0f
Create Date: 2026-06-09 14:01:39.746116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f4a9cd923b'
down_revision: Union[str, None] = '265c50853d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relay_config', sa.Column('device_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'relay_config', 'hardware_devices', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relay_config', type_='foreignkey')
    op.drop_column('relay_config', 'device_id')
    # ### end Alembic commands ###