"""Add RolePolicy table

Revision ID: 22688a4bc3fd
Revises: 21a5a21efc5a
Create Date: 2026-05-15 15:01:41.100311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22688a4bc3fd'
down_revision: Union[str, None] = '21a5a21efc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###