"""add_is_online_and_last_seen_to_hardware_devices

Revision ID: 265c50853d0f
Revises: 33b3c12acf4a
Create Date: 2026-06-09 11:41:33.435008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265c50853d0f'
down_revision: Union[str, None] = '33b3c12acf4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###