"""add_is_online_last_seen_to_hardware_devices

Revision ID: 33b3c12acf4a
Revises: 3cb245533be3
Create Date: 2026-06-09 11:25:20.121083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b3c12acf4a'
down_revision: Union[str, None] = '3cb245533be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hardware_devices', sa.Column('is_online', sa.Boolean(), nullable=False))
    op.add_column('hardware_devices', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hardware_devices', 'last_seen')
    op.drop_column('hardware_devices', 'is_online')
    # ### end Alembic commands ###