"""Add desired state on relay config table

Revision ID: 3cb245533be3
Revises: d4daa1874917
Create Date: 2026-06-08 20:48:52.122007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb245533be3'
down_revision: Union[str, None] = 'd4daa1874917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relay_config', sa.Column('desired_state', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relay_config', 'desired_state')
    # ### end Alembic commands ###