"""Add owner_id to SensorData

Revision ID: 50b3475782d4
Revises: 60862e7ba531
Create Date: 2026-05-31 18:40:37.168852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b3475782d4'
down_revision: Union[str, None] = '60862e7ba531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sensor_data', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_data', type_='foreignkey')
    op.drop_column('sensor_data', 'owner_id')
    # ### end Alembic commands ###