"""Add relay owner and avatar

Revision ID: 60862e7ba531
Revises: 83b2c7a5f988
Create Date: 2026-05-24 19:09:48.408877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60862e7ba531'
down_revision: Union[str, None] = '83b2c7a5f988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relay_config', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'relay_config', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_constraint(None, 'relay_config', type_='foreignkey')
    op.drop_column('relay_config', 'owner_id')
    # ### end Alembic commands ###