"""Add RolePolicy table

Revision ID: 83b2c7a5f988
Revises: 22688a4bc3fd
Create Date: 2026-05-15 15:26:11.972127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b2c7a5f988'
down_revision: Union[str, None] = '22688a4bc3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_policies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('allowed_endpoints', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_role_policies_name'), 'role_policies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_policies_name'), table_name='role_policies')
    op.drop_table('role_policies')
    # ### end Alembic commands ###