"""Added missing pin columns

Revision ID: 9a592227c01a
Revises: a9e3bbde67eb
Create Date: 2026-06-11 08:23:39.851270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a592227c01a'
down_revision: Union[str, None] = 'a9e3bbde67eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###