"""added physical pin

Revision ID: a9e3bbde67eb
Revises: 21f4a9cd923b
Create Date: 2026-06-11 07:45:37.682664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e3bbde67eb'
down_revision: Union[str, None] = '21f4a9cd923b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relay_config', sa.Column('physical_pin', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('relay_config', sa.Column('threshold', sa.Float(), nullable=True))
    op.add_column('relay_config', sa.Column('threshold_unit', sa.String(), nullable=True, server_default='A'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relay_config', 'threshold_unit')
    op.drop_column('relay_config', 'threshold')
    op.drop_column('relay_config', 'physical_pin')
    # ### end Alembic commands ###