"""Recreate ML tables with timezone fix

Revision ID: f964139b99ce
Revises: c46ab04af721
Create Date: 2026-06-07 01:39:56.943094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f964139b99ce'
down_revision: Union[str, None] = 'c46ab04af721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumption_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('target_monthly_kwh', sa.Float(), nullable=False),
    sa.Column('target_monthly_cost', sa.Float(), nullable=False),
    sa.Column('valid_for_month', sa.Integer(), nullable=False),
    sa.Column('valid_for_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'valid_for_month', 'valid_for_year', name='uix_user_target')
    )
    op.create_index(op.f('ix_consumption_targets_id'), 'consumption_targets', ['id'], unique=False)
    op.create_table('daily_energy_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('total_kwh', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('peak_power_w', sa.Float(), nullable=True),
    sa.Column('avg_power_w', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'summary_date', name='uix_user_daily_date')
    )
    op.create_index(op.f('ix_daily_energy_summary_id'), 'daily_energy_summary', ['id'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_cost_eod', sa.Float(), nullable=False),
    sa.Column('predicted_cost_eom', sa.Float(), nullable=False),
    sa.Column('required_daily_reduction_kwh', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_id'), 'ml_predictions', ['id'], unique=False)
    op.create_table('monthly_energy_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_kwh', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('peak_power_w', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'month', 'year', name='uix_user_monthly')
    )
    op.create_index(op.f('ix_monthly_energy_summary_id'), 'monthly_energy_summary', ['id'], unique=False)
    op.create_table('tariff_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('rate_per_kwh', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_plans_id'), 'tariff_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariff_plans_id'), table_name='tariff_plans')
    op.drop_table('tariff_plans')
    op.drop_index(op.f('ix_monthly_energy_summary_id'), table_name='monthly_energy_summary')
    op.drop_table('monthly_energy_summary')
    op.drop_index(op.f('ix_ml_predictions_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_daily_energy_summary_id'), table_name='daily_energy_summary')
    op.drop_table('daily_energy_summary')
    op.drop_index(op.f('ix_consumption_targets_id'), table_name='consumption_targets')
    op.drop_table('consumption_targets')
    # ### end Alembic commands ###