import os
import logging
from datetime import datetime
import urllib.request
import json
import resend

logger = logging.getLogger(__name__)

# Load the Resend API Key
resend.api_key = os.getenv("RESEND_API_KEY")

def generate_cyber_html(display_name: str, body_text: str, button_text: str = None, button_url: str = None) -> str:
    """Generates the dark-mode HTML payload with a text-heavy security footer."""
    logo_url = "https://i.postimg.cc/HjGphmVB/full-logo.png"
    
    button_html = ""
    if button_text and button_url:
        button_html = f"""
        <tr>
            <td align="center" style="padding: 0 40px 30px 40px;">
                <a href="{button_url}" style="background-color: #00f0ff; color: #050508; font-weight: bold; font-family: 'Segoe UI', Tahoma, sans-serif; text-decoration: none; padding: 14px 28px; border-radius: 4px; text-transform: uppercase; letter-spacing: 1.5px; display: inline-block; border: 1px solid #7ee8ce; box-shadow: 0 0 10px rgba(0, 240, 255, 0.3);">
                    {button_text}
                </a>
            </td>
        </tr>
        """
    
    return f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="background-color: #050508; color: #cdd6f4; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 40px 10px;">
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 550px; background-color: #0b0f19; border: 1px solid #1a2332; border-radius: 6px; border-top: 3px solid #00f0ff;">
            <tr>
                <td align="center" style="padding: 35px 0 20px 0; background-color: #080a10;">
                    <img src="{logo_url}" alt="PowerSense" style="display: block; width: 100%; max-width: 480px; height: auto; border-radius: 8px;">
                </td>
            </tr>
            <tr>
                <td style="padding: 0 40px 30px 40px;">
                    <h2 style="color: #ffffff; font-size: 18px; margin-bottom: 25px; font-weight: 600; text-transform: uppercase; letter-spacing: 2px;">System Notice _ //</h2>
                    <p style="font-size: 15px; line-height: 1.6; margin-bottom: 20px; color: #8ba4b5;">
                        Initiating sequence for user: <br>
                        <strong style="color: #00f0ff; font-size: 18px;">{display_name}</strong>
                    </p>
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: #0d131f; border-left: 2px solid #00f0ff; margin-bottom: 30px;">
                        <tr>
                            <td style="padding: 15px;">
                                <p style="font-size: 14px; line-height: 1.6; margin: 0; color: #a1b8c7;">{body_text}</p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            {button_html}
            <tr>
                <td style="padding: 0 40px 30px 40px;">
                    <p style="font-size: 13px; line-height: 1.5; color: #4e6a7c; margin-top: 0;">
                        Stay energized,<br><span style="color: #00f0ff; font-weight: 600;">[ The PowerSense Team ]</span>
                    </p>
                </td>
            </tr>
            <tr>
                <td style="padding: 20px 40px 30px 40px; background-color: #080a10; border-top: 1px solid #1a2332;">
                    <p style="font-size: 10px; line-height: 1.5; color: #3a4b5c; margin: 0; text-align: justify;">
                        <strong>SECURITY PROTOCOL // CONFIDENTIAL TRANSMISSION</strong><br><br>
                        This automated transmission was generated by the PowerSense Identity Management System. You are receiving this communication because this email address is registered and authorized to access a PowerSense IoT monitoring node. This email and any associated security tokens are strictly confidential. If you did not authorize this account creation, or if you believe your credentials have been compromised, please contact your system administrator immediately or execute a secure password reset protocol via your dashboard. PowerSense will never ask for your plaintext password via email.
                    </p>
                </td>
            </tr>
        </table>
    </body>
    </html>
    """

def dispatch_resend_email(to_email: str, subject: str, html_content: str):
    """Fires the API payload to Resend."""
    if not resend.api_key:
        logger.warning("⚠️ RESEND_API_KEY missing. Email aborted.")
        return

    try:
        response = resend.Emails.send({
            "from": "PowerSense Security <security@powersense.top>", 
            "to": to_email,
            "subject": subject,
            "html": html_content
        })
        logger.info(f"✅ Secure API email dispatched to {to_email}. Resend ID: {response.get('id')}")
    except Exception as e:
        logger.error(f"❌ Resend API Transmission failed for {to_email}: {str(e)}")

def get_location_from_ip(ip_address: str) -> str:
    if ip_address in ["127.0.0.1", "::1", "localhost"]:
        return "Local Network (Localhost)"
    try:
        url = f"http://ip-api.com/json/{ip_address}"
        req = urllib.request.Request(url, headers={'User-Agent': 'PowerSense-Security'})
        with urllib.request.urlopen(req, timeout=3) as response:
            data = json.loads(response.read().decode())
            if data.get("status") == "success":
                return f"{data.get('city', 'Unknown')}, {data.get('country', 'Unknown')}"
    except Exception:
        pass
    return "Unknown Location"

# ==========================================
# PUBLIC EVENT TRIGGERS
# ==========================================

def send_welcome_email(to_email: str, full_name: str):
    display = full_name if full_name else "User"
    body = "Welcome to the grid. Your identity has been verified and registered. You now have secure access to monitor IoT telemetry and command relay nodes."
    html = generate_cyber_html(display, body)
    dispatch_resend_email(to_email, "Welcome to PowerSense ⚡", html)

def send_login_alert_email(to_email: str, full_name: str, ip_address: str, location: str):
    display = full_name if full_name else "User"
    login_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    frontend_url = os.getenv("FRONTEND_URL", "https://powersense.top").rstrip("/")
    
    body = f"""
    A new session was authenticated for your profile. <br><br>
    <div style="background-color: #080a10; padding: 15px; border-radius: 4px; border-left: 2px solid #39ff14; font-family: monospace; font-size: 14px; margin-bottom: 20px;">
        <span style="color: #4e6a7c;">TIMESTAMP :</span> <span style="color: #cdd6f4;">{login_time}</span><br>
        <span style="color: #4e6a7c;">IP_ADDRESS:</span> <span style="color: #00f0ff;">{ip_address}</span><br>
        <span style="color: #4e6a7c;">LOCATION  :</span> <span style="color: #cdd6f4;">{location}</span>
    </div>
    If this was you, no action is required.
    """
    
    html = generate_cyber_html(
        display_name=display, 
        body_text=body,
        button_text="Not You? Reset Password",
        button_url=f"{frontend_url}/forgot-password"
    )
    dispatch_resend_email(to_email, "Security Alert: Session Authenticated 🛡️", html)

def send_password_reset_email(to_email: str, full_name: str, token: str):
    display = full_name if full_name else "User"
    frontend_url = os.getenv("FRONTEND_URL", "https://powersense.top").rstrip("/")
    reset_link = f"{frontend_url}/reset-password?token={token}"
    
    body = "A password reset protocol was initiated for your account. This link will expire in 15 minutes. If you did not request this, you can safely ignore this email; your security remains intact."
    
    html = generate_cyber_html(
        display_name=display, 
        body_text=body,
        button_text="Reset Password",
        button_url=reset_link
    )
    dispatch_resend_email(to_email, "Action Required: Password Reset Request 🔑", html)


def send_profile_update_email(to_email: str, full_name: str, ip_address: str):
    """Dispatched when a user changes their name or profile details."""
    display = full_name if full_name else "User"
    update_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    location = get_location_from_ip(ip_address) # Lookup runs securely in background thread
    
    body = f"""
    Your identity parameters (Profile Information) were recently updated. <br><br>
    <div style="background-color: #080a10; padding: 15px; border-radius: 4px; border-left: 2px solid #00f0ff; font-family: monospace; font-size: 14px; margin-bottom: 20px;">
        <span style="color: #4e6a7c;">TIMESTAMP :</span> <span style="color: #cdd6f4;">{update_time}</span><br>
        <span style="color: #4e6a7c;">IP_ADDRESS:</span> <span style="color: #00f0ff;">{ip_address}</span><br>
        <span style="color: #4e6a7c;">LOCATION  :</span> <span style="color: #cdd6f4;">{location}</span>
    </div>
    If you authorized this modification, no further action is required.
    """
    
    html = generate_cyber_html(display, body)
    dispatch_resend_email(to_email, "System Notice: Profile Updated 👤", html)


def send_password_changed_email(to_email: str, full_name: str, ip_address: str):
    """Dispatched upon a successful password change."""
    display = full_name if full_name else "User"
    change_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    location = get_location_from_ip(ip_address)
    frontend_url = os.getenv("FRONTEND_URL", "https://powersense.top").rstrip("/")
    
    body = f"""
    The master password for your grid access has been successfully changed. <br><br>
    <div style="background-color: #080a10; padding: 15px; border-radius: 4px; border-left: 2px solid #ff003c; font-family: monospace; font-size: 14px; margin-bottom: 20px;">
        <span style="color: #4e6a7c;">TIMESTAMP :</span> <span style="color: #cdd6f4;">{change_time}</span><br>
        <span style="color: #4e6a7c;">IP_ADDRESS:</span> <span style="color: #00f0ff;">{ip_address}</span><br>
        <span style="color: #4e6a7c;">LOCATION  :</span> <span style="color: #cdd6f4;">{location}</span>
    </div>
    If you did NOT perform this action, your credentials have been compromised. Immediately secure your account using the link below.
    """
    
    html = generate_cyber_html(
        display_name=display, 
        body_text=body,
        button_text="Secure Account Now",
        button_url=f"{frontend_url}/forgot-password"
    )
    dispatch_resend_email(to_email, "SECURITY ALERT: Password Modified ⚠️", html)